backend:
  name: git-gateway
  branch: master
media_folder: "images"
collections:
  - name: "evaluations"
    label: "Evaluations"
    folder: "_evaluations"
    create: true
    slug: "{{first_name}_{last_name}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "evaluation"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Header", name: "header", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
